package com.wardellbagby.sensordisabler.util;

import android.content.Context;
import android.os.Environment;
import android.util.Log;
import androidx.annotation.Nullable;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Utility class for reading sensor data from custom text files.
 * 
 * The text file format is:
 * # Comments start with #
 * SensorKey=value1:value2:value3
 * 
 * Where SensorKey is the unique sensor key generated by SensorUtil.generateUniqueSensorKey()
 * and values are colon-separated float values for mocking the sensor.
 *
 * @author Sensor Disabler Team
 */
public final class SensorDataFileReader {

  private static final String TAG = "SensorDataFileReader";
  private static final String VALUE_SEPARATOR = ":";
  private static final String KEY_VALUE_SEPARATOR = "=";
  private static final String COMMENT_PREFIX = "#";

  private SensorDataFileReader() {
    // Utility class
  }

  /**
   * Reads sensor data from a text file.
   *
   * @param context The application context
   * @param fileName The name of the file to read (should be in the sensor disabler directory)
   * @return A map of sensor keys to float arrays, or null if the file couldn't be read
   */
  @Nullable
  public static Map<String, float[]> readSensorDataFromFile(Context context, String fileName) {
    File file = getSensorDataFile(fileName);
    
    if (!file.exists() || !file.canRead()) {
      Log.w(TAG, "Sensor data file does not exist or cannot be read: " + file.getAbsolutePath());
      return null;
    }

    Map<String, float[]> sensorDataMap = new HashMap<>();
    
    try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
      String line;
      int lineNumber = 0;
      
      while ((line = reader.readLine()) != null) {
        lineNumber++;
        line = line.trim();
        
        // Skip empty lines and comments
        if (line.isEmpty() || line.startsWith(COMMENT_PREFIX)) {
          continue;
        }
        
        // Parse the line
        String[] parts = line.split(KEY_VALUE_SEPARATOR, 2);
        if (parts.length != 2) {
          Log.w(TAG, "Invalid line format at line " + lineNumber + ": " + line);
          continue;
        }
        
        String sensorKey = parts[0].trim();
        String valuesString = parts[1].trim();
        
        try {
          float[] values = parseValues(valuesString);
          sensorDataMap.put(sensorKey, values);
          Log.d(TAG, "Loaded sensor data for key: " + sensorKey + " with " + values.length + " values");
        } catch (NumberFormatException e) {
          Log.w(TAG, "Invalid values at line " + lineNumber + ": " + valuesString, e);
        }
      }
      
      Log.i(TAG, "Successfully loaded " + sensorDataMap.size() + " sensor configurations from " + fileName);
      return sensorDataMap;
      
    } catch (IOException e) {
      Log.e(TAG, "Error reading sensor data file: " + file.getAbsolutePath(), e);
      return null;
    }
  }

  /**
   * Parses a colon-separated string of float values.
   *
   * @param valuesString The string to parse (e.g., "1.0:2.0:3.0")
   * @return An array of float values
   * @throws NumberFormatException if any value cannot be parsed as a float
   */
  private static float[] parseValues(String valuesString) throws NumberFormatException {
    String[] valueStrings = valuesString.split(VALUE_SEPARATOR);
    float[] values = new float[valueStrings.length];
    
    for (int i = 0; i < valueStrings.length; i++) {
      values[i] = Float.parseFloat(valueStrings[i].trim());
    }
    
    return values;
  }

  /**
   * Gets the sensor data file from the appropriate directory.
   *
   * @param fileName The name of the file
   * @return The File object
   */
  private static File getSensorDataFile(String fileName) {
    // Store in the app's directory in external storage
    File sensorDisablerDir = new File(
        Environment.getExternalStorageDirectory(),
        Constants.SENSOR_DATA_DIRECTORY
    );
    
    // Create directory if it doesn't exist
    if (!sensorDisablerDir.exists()) {
      sensorDisablerDir.mkdirs();
    }
    
    return new File(sensorDisablerDir, fileName);
  }

  /**
   * Gets sensor values for a specific sensor key from the file.
   *
   * @param context The application context
   * @param fileName The name of the file to read
   * @param sensorKey The unique sensor key
   * @return The float array of values, or null if not found
   */
  @Nullable
  public static float[] getSensorValuesFromFile(Context context, String fileName, String sensorKey) {
    Map<String, float[]> sensorDataMap = readSensorDataFromFile(context, fileName);
    
    if (sensorDataMap == null) {
      return null;
    }
    
    return sensorDataMap.get(sensorKey);
  }
}
